Holonet.Jedi.Academy.App/Controllers/ExperienceController.cs
using Holonet.Jedi.Academy.App.Areas.Identity.Data;
using Holonet.Jedi.Academy.App.Areas.Identity.Enums;
using Holonet.Jedi.Academy.App.Middleware;
using Holonet.Jedi.Academy.Entities;
using Holonet.Jedi.Academy.Entities.App;
using Holonet.Jedi.Academy.Entities.Configuration;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;

namespace Holonet.Jedi.Academy.App.Controllers
{
	[Route("api/experience")]
	[Produces("application/json")]
	[ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
	[ApiController]
	public class ExperienceController : ControllerDefaults
	{
		private readonly ILogger<ExperienceController> _logger;
		private readonly Holonet.Jedi.Academy.BL.Data.AcademyContext _context;
		private readonly UserManager<JediAcademyAppUser> _userManager;
		private readonly IRazorPartialToStringRenderer _renderer;

		public ExperienceController(ILogger<ExperienceController> logger, Holonet.Jedi.Academy.BL.Data.AcademyContext context, UserManager<JediAcademyAppUser> userManager, IRazorPartialToStringRenderer renderer, IOptions<SiteConfiguration> options, IHttpContextAccessor httpContextAccessor) : base(options, httpContextAccessor)
		{
			_logger = logger;
			_context = context;
			_userManager = userManager;
			_renderer = renderer;
		}

		[Route("GetIndexPage")]
		[HttpPost]
		public async Task<IActionResult> GetIndexPage([FromBody] JObject data)
		{
			if (data == null || data["textFilter"] == null || data["firstItem"] == null || data["completed"] == null)
			{
				return StatusCode(StatusCodes.Status500InternalServerError, new Exception("Expected parameters were not found in the request."));
			}
			try
			{
				string textFilter = data["textFilter"].ToObject<string>();
				bool? completed = data["completed"].ToObject<bool?>();
				int firstItem = data["firstItem"].ToObject<int>();
				UserAccount? currentUser = GetActiveUser();
				if (currentUser == null)
				{
					throw new Exception("A valid user account was not detected.");
				}

				bool canCreateEdit = await CanCreateEditItem();

				IQueryable<Knowledge>? knowledgeOpsIQ = null;
				if (canCreateEdit)
				{
					knowledgeOpsIQ = from ko in _context.KnowledgeOpportunities
									 from kl in _context.KnowledgeLearned.Where(x => x.KnowledgeId == ko.Id && x.StudentId.Equals(GetStudentId(currentUser)) && x.CompletedOn.HasValue).DefaultIfEmpty()
									 select new Knowledge()
									 {
										 Id = ko.Id,
										 Name = ko.Name,
										 ExperienceToGain = ko.ExperienceToGain,
										 Description = ko.Description,
										 Archived = ko.Archived,
										 CreatedOn = ko.CreatedOn,
										 HasUserCompleted = kl.CompletedOn.HasValue,
										 CanUserCreateEdit = canCreateEdit
									 };
				}
				else
				{
					knowledgeOpsIQ = from ko in _context.KnowledgeOpportunities.Where(ko => !ko.Archived)
									 from kl in _context.KnowledgeLearned.Where(x=>x.KnowledgeId==ko.Id && x.StudentId.Equals(GetStudentId(currentUser)) && x.CompletedOn.HasValue).DefaultIfEmpty()
									 select new Knowledge()
									 {
										 Id = ko.Id,
										 Name = ko.Name,
										 ExperienceToGain = ko.ExperienceToGain,
										 Description = ko.Description,
										 Archived = ko.Archived,
										 CreatedOn = ko.CreatedOn,
										 HasUserCompleted = kl.CompletedOn.HasValue,
										 CanUserCreateEdit = canCreateEdit
									 };
				}
				if (!String.IsNullOrEmpty(textFilter))
				{
					knowledgeOpsIQ = knowledgeOpsIQ.Where(x => x.Name.ToUpper().Contains(textFilter.ToUpper()));
				}

				if (completed.HasValue)
				{
					knowledgeOpsIQ = knowledgeOpsIQ.Where(x => x.HasUserCompleted.Equals(completed));
				}

				knowledgeOpsIQ = knowledgeOpsIQ.OrderByDescending(s => s.CreatedOn);
				var pageSize = (Config.SiteSettings != null) ? Config.SiteSettings.PageSize : 10;
				// Extract a portion of data
				var pageData = await knowledgeOpsIQ.Skip(firstItem).Take(pageSize).ToListAsync();
				if (pageData == null || pageData.Count() == 0)
					return StatusCode(204);  // 204 := "No Content"
				var content = await _renderer.RenderPartialToStringAsync("~/Pages/Experience/_Index.cshtml", pageData);
				return Ok(content);
			}
			catch (Exception ex)
			{
				return StatusCode(StatusCodes.Status500InternalServerError, ex);
			}
		}

		private int GetStudentId(UserAccount currentUser)
		{
			int studentId = -1;
			var userProfileDomain = _context.UserProfiles.Where(x => x.UserId.Equals(currentUser.UserId)).FirstOrDefault();
			if (userProfileDomain != null)
			{
				studentId = userProfileDomain.StudentId;
			}
			return studentId;
		}

		private async Task<bool> CanCreateEditItem()
		{
			JediAcademyAppUser user = await _userManager.GetUserAsync(User);
			return await _userManager.IsInRoleAsync(user, Roles.Administrator.ToString());
		}
	}
}

Holonet.Jedi.Academy.App/Pages/Experience/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Holonet.Jedi.Academy.BL.Data;
using Holonet.Jedi.Academy.Entities.App;
using Holonet.Jedi.Academy.App.Areas.Identity.Enums;
using Microsoft.AspNetCore.Authorization;
using Holonet.Jedi.Academy.App.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Holonet.Jedi.Academy.Entities.Configuration;
using Microsoft.Extensions.Options;
using Holonet.Jedi.Academy.Entities;

namespace Holonet.Jedi.Academy.App.Pages.Experience
{
	[Authorize(Roles = "Administrator, Instructor")]
	public class CreateModel : RazorPageDefaults
	{
		private readonly Holonet.Jedi.Academy.BL.Data.AcademyContext _context;
		private readonly UserManager<JediAcademyAppUser> _userManager;

		public CreateModel(Holonet.Jedi.Academy.BL.Data.AcademyContext context, UserManager<JediAcademyAppUser> userManager, IOptions<SiteConfiguration> options, IHttpContextAccessor httpContextAccessor) : base(options, httpContextAccessor)
		{
			_context = context;
			_userManager = userManager;
		}

		public bool CanCreateEdit { get; set; } = false;

		public async Task<IActionResult> OnGetAsync()
		{
			UserAccount? currentUser = GetActiveUser();
			if (currentUser == null)
			{
				throw new Exception("A valid user account was not detected.");
			}

			CanCreateEdit = await CanCreateEditItem();
			return Page();
		}

		[BindProperty]
		public Knowledge Knowledge { get; set; } = default!;


		// To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
		public async Task<IActionResult> OnPostAsync()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			var emptyKnowledge = new Knowledge();

			if (await TryUpdateModelAsync<Knowledge>(
				emptyKnowledge,
				"knowledge",   // Prefix for form value.
				s => s.Name, s => s.ExperienceToGain, s => s.Description))
			{
				_context.KnowledgeOpportunities.Add(emptyKnowledge);
				await _context.SaveChangesAsync();
				return RedirectToPage("./Index");
			}

			return Page();
		}

		private async Task<bool> CanCreateEditItem()
		{
			JediAcademyAppUser user = await _userManager.GetUserAsync(User);
			return await _userManager.IsInRoleAsync(user, Roles.Administrator.ToString());
		}
	}
}

Holonet.Jedi.Academy.App/Pages/Experience/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Holonet.Jedi.Academy.BL.Data;
using Holonet.Jedi.Academy.Entities.App;
using Holonet.Jedi.Academy.App.Areas.Identity.Enums;
using Microsoft.AspNetCore.Authorization;

namespace Holonet.Jedi.Academy.App.Pages.Experience
{
	[Authorize(Roles = "Administrator, Instructor")]
	public class DeleteModel : PageModel
    {
        private readonly Holonet.Jedi.Academy.BL.Data.AcademyContext _context;

        public DeleteModel(Holonet.Jedi.Academy.BL.Data.AcademyContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Knowledge Knowledge { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.KnowledgeOpportunities == null)
            {
                return NotFound();
            }

            var knowledge = await _context.KnowledgeOpportunities.FirstOrDefaultAsync(m => m.Id == id);

            if (knowledge == null)
            {
                return NotFound();
            }
            else 
            {
                Knowledge = knowledge;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.KnowledgeOpportunities == null)
            {
                return NotFound();
            }
            var knowledge = await _context.KnowledgeOpportunities.FindAsync(id);

            if (knowledge != null)
            {
                Knowledge = knowledge;
                _context.KnowledgeOpportunities.Remove(Knowledge);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Holonet.Jedi.Academy.App/Pages/Experience/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Holonet.Jedi.Academy.BL.Data;
using Holonet.Jedi.Academy.Entities.App;
using Holonet.Jedi.Academy.App.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Holonet.Jedi.Academy.Entities.Configuration;
using Microsoft.Extensions.Options;
using Holonet.Jedi.Academy.App.Areas.Identity.Enums;
using Holonet.Jedi.Academy.Entities;
using Holonet.Jedi.Academy.BL.Quests;
using Holonet.Jedi.Academy.Entities.Models;

namespace Holonet.Jedi.Academy.App.Pages.Experience
{
    public class DetailsModel : RazorPageDefaults
    {
        private readonly Holonet.Jedi.Academy.BL.Data.AcademyContext _context;
		private readonly UserManager<JediAcademyAppUser> _userManager;

		public DetailsModel(Holonet.Jedi.Academy.BL.Data.AcademyContext context, UserManager<JediAcademyAppUser> userManager, IOptions<SiteConfiguration> options, IHttpContextAccessor httpContextAccessor) : base(options, httpContextAccessor)
		{
			_context = context;
			_userManager = userManager;
		}

		public Knowledge Knowledge { get; set; } = default!;
		public int ID { get; set; }
		public KnowledgeXP KnowledgeParticipation { get; set; } = default!;

		public bool CanJoin { get; set; } = false;
		public bool CanCreateEdit { get; set; } = false;

		public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.KnowledgeOpportunities == null)
            {
                return NotFound();
            }

			UserAccount? currentUser = GetActiveUser();
			if (currentUser == null)
			{
				throw new Exception("A valid user account was not detected.");
			}
			ID = id.Value;
			CanCreateEdit = await CanCreateEditItem();

			var knowledge = await _context.KnowledgeOpportunities.FirstOrDefaultAsync(m => m.Id == id);
            if (knowledge == null)
            {
                return NotFound();
            }
            else 
            {
                Knowledge = knowledge;
			}
			KnowledgeParticipation = await _context.KnowledgeLearned
				.Where(x => x.KnowledgeId.Equals(id) && x.StudentId.Equals(GetStudentId(currentUser)))
				.FirstOrDefaultAsync();
			CanJoin = (KnowledgeParticipation == null) ? true : false;
			return Page();
        }

		public async Task<IActionResult> OnPostCompleteAsync(int? id)
		{
			if (id == null || _context.KnowledgeLearned == null)
			{
				return NotFound();
			}
			ID = id.Value;
			UserAccount? currentUser = GetActiveUser();
			if (currentUser == null)
			{
				return NotFound();
			}
			int studentId = GetStudentId(currentUser);
			KnowledgeParticipation = await _context.KnowledgeLearned
				.Include(k => k.Knowledge)
				.Where(x => x.KnowledgeId.Equals(id) && x.StudentId.Equals(studentId)).FirstOrDefaultAsync();
			if (KnowledgeParticipation != null)
			{
				ParticipationHandler quests = new ParticipationHandler(_context);
				if (!await quests.MarkAsCompleteAsync(KnowledgeParticipation))
				{
					throw new Exception("Unable to mark this experience as complete.");
				}
				if (!await quests.UpdateExperienceAsync(KnowledgeParticipation, studentId))
				{
					throw new Exception("Unable to update the experience value for the user.");
				}
				RankHandler ranking = new RankHandler(_context);
				if (await ranking.IsEligible(studentId))
				{
					await ranking.RankUp(studentId);
				}
			}
			else
			{
				throw new Exception("You are not participating in this experience yet.");
			}
			return RedirectToPage("Details", new { id = ID });
		}

		public async Task<IActionResult> OnPostJoinAsync(int? id)
		{
			if (id == null || _context.KnowledgeOpportunities == null || _context.KnowledgeLearned == null)
			{
				return NotFound();
			}
			ID = id.Value;
			UserAccount? currentUser = GetActiveUser();
			if (currentUser == null)
			{
				return NotFound();
			}
			var knowledgeOp = await _context.KnowledgeOpportunities.FirstOrDefaultAsync(m => m.Id == id);
			if (knowledgeOp == null)
			{
				return NotFound();
			}
			KnowledgeParticipation = await _context.KnowledgeLearned.Where(x => x.KnowledgeId.Equals(id) && x.StudentId.Equals(GetStudentId(currentUser))).FirstOrDefaultAsync();
			CanJoin = (KnowledgeParticipation == null) ? true : false;
			if (CanJoin)
			{
				var emptyKnowledgeParticipation = new KnowledgeXP();
				emptyKnowledgeParticipation.KnowledgeId = ID;
				emptyKnowledgeParticipation.StartedOn = DateTime.Now;
				emptyKnowledgeParticipation.StudentId = GetStudentId(currentUser);
				emptyKnowledgeParticipation.ExperienceToGain = knowledgeOp.ExperienceToGain;

				_context.KnowledgeLearned.Add(emptyKnowledgeParticipation);
				await _context.SaveChangesAsync();
			}
			else
			{
				//throw error, can't participate yet
			}
			return RedirectToPage("Details", new { id = ID });
		}

		public async Task<IActionResult> OnPostLeaveAsync(int? id)
		{
			if (id == null || _context.KnowledgeLearned == null)
			{
				return NotFound();
			}
			ID = id.Value;
			UserAccount? currentUser = GetActiveUser();
			if (currentUser == null)
			{
				return NotFound();
			}

			KnowledgeParticipation = await _context.KnowledgeLearned.Where(x => x.KnowledgeId.Equals(id) && x.StudentId.Equals(GetStudentId(currentUser))).FirstOrDefaultAsync();
			if (KnowledgeParticipation != null)
			{
				_context.KnowledgeLearned.Remove(KnowledgeParticipation);
				await _context.SaveChangesAsync();
			}
			else
			{
				//throw error, not participating, so can't leave
			}
			return RedirectToPage("Details", new { id = ID });
		}

		private async Task<bool> CanCreateEditItem()
		{
			JediAcademyAppUser user = await _userManager.GetUserAsync(User);
			return await _userManager.IsInRoleAsync(user, Roles.Administrator.ToString());
		}

		private int GetStudentId(UserAccount currentUser)
		{
			int studentId = -1;
			var userProfileDomain = _context.UserProfiles.Where(x => x.UserId.Equals(currentUser.UserId)).FirstOrDefault();
			if (userProfileDomain != null)
			{
				studentId = userProfileDomain.StudentId;
			}
			return studentId;
		}

		//private bool EvaluateKnowOpEligibility(UserAccount currentUser, Knowledge aKnowledge)
		//{
		//	bool canParticipate = false;
		//	var userProfileDomain = _context.UserProfiles.Include(x => x.Student).Where(x => x.UserId.Equals(currentUser.UserId)).FirstOrDefault();
		//	if (userProfileDomain != null && userProfileDomain.Student != null && aKnowledge != null)
		//	{
		//		if (userProfileDomain.Student.Rank.RankLevel >= aQuest.Rank.RankLevel)
		//		{
		//			canParticipate = true;
		//		}
		//	}

		//	return canParticipate;
		//}
	}
}

Holonet.Jedi.Academy.App/Pages/Experience/Index.cshtml.cs
using Microsoft.EntityFrameworkCore;
using Holonet.Jedi.Academy.Entities;
using Holonet.Jedi.Academy.Entities.App;
using Holonet.Jedi.Academy.Entities.Configuration;
using Microsoft.Extensions.Options;
using Holonet.Jedi.Academy.App.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Holonet.Jedi.Academy.App.Areas.Identity.Enums;

namespace Holonet.Jedi.Academy.App.Pages.Experience
{
    public class IndexModel : RazorPageDefaults
    {
        private readonly Holonet.Jedi.Academy.BL.Data.AcademyContext _context;
		private readonly UserManager<JediAcademyAppUser> _userManager;

		public IndexModel(Holonet.Jedi.Academy.BL.Data.AcademyContext context, UserManager<JediAcademyAppUser> userManager, IOptions<SiteConfiguration> options, IHttpContextAccessor httpContextAccessor) : base(options, httpContextAccessor)
        {
            _context = context;
			_userManager = userManager;
		}

		public bool CanCreateEdit { get; set; } = false;

		public async Task OnGetAsync()
        {
			UserAccount? currentUser = GetActiveUser();
			if (currentUser == null)
			{
				throw new Exception("A valid user account was not detected.");
			}

			CanCreateEdit = await CanCreateEditItem();
        }

		private async Task<bool> CanCreateEditItem()
		{
			JediAcademyAppUser user = await _userManager.GetUserAsync(User);
			return await _userManager.IsInRoleAsync(user, Roles.Administrator.ToString());
		}
	}
}

Holonet.Jedi.Academy.App/Pages/Experience/Details.cshtml
@page
@model Holonet.Jedi.Academy.App.Pages.Experience.DetailsModel

@{
	ViewData["Title"] = "Experience Details";
}
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
	<symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
		<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
	</symbol>
	<symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
		<path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
	</symbol>
	<symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
		<path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
	</symbol>
</svg>
<h1>@Html.DisplayFor(model => model.Knowledge.Name)</h1>
<hr />
<div class="row">
	<div class="col-6">
		<div class="card">
			<div class="card-header">
				<h5>Basic Information</h5>
			</div>
			<div class="card-body">
				<dl class="row">
					<dt class="col-sm-3">
						@Html.DisplayNameFor(model => model.Knowledge.ExperienceToGain)
					</dt>
					<dd class="col-sm-9">
						<span class="badge bg-secondary">+@Html.DisplayFor(model => model.Knowledge.ExperienceToGain)</span> (Currently)
					</dd>
					<dt class="col-sm-3">
						@Html.DisplayNameFor(model => model.Knowledge.Description)
					</dt>
					<dd class="col-sm-9">
						@Html.DisplayFor(model => model.Knowledge.Description)
					</dd>
				</dl>
			</div>
			<div class="card-footer">
				@if (Model.CanCreateEdit)
				{
					<a asp-page="./Edit" asp-route-id="@Model.Knowledge?.Id" class="btn btn-secondary">Edit</a> <text>|</text>
				}
				<a asp-page="./Index">Back to List</a>
			</div>
		</div>
	</div>
	<div class="col-6">
		<form method="post" asp-page-handler="complete" asp-route-id="@Model.ID">
			<div class="card">
				<div class="card-header">
					<h5>Availability</h5>
				</div>
				<div class="card-body">
					<div class="row">
						<div class="col">
							@if (Model.KnowledgeParticipation != null)
							{
								if (Model.KnowledgeParticipation.IsComplete)
								{
									<div class="alert alert-success d-flex align-items-center" role="alert">
										<svg class="bi flex-shrink-0" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill" /></svg>
										<div class="mx-2 fst-italic small">
											You completed this experience on @Html.DisplayFor(model => model.KnowledgeParticipation.CompletedOn) and earned <span class="badge bg-secondary">+@Html.DisplayFor(model => model.KnowledgeParticipation.ExperienceToGain)</span> experience.
										</div>
									</div>
								}
								else
								{
									<div class="alert alert-secondary d-flex align-items-center " role="alert">
										<svg class="bi flex-shrink-0" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill" /></svg>
										<div class="mx-2 fst-italic small">
											You began this experience on @Html.DisplayFor(model => model.KnowledgeParticipation.StartedOn) and will earn <span class="badge bg-secondary">+@Html.DisplayFor(model => model.KnowledgeParticipation.ExperienceToGain)</span> experience.
										</div>
										
									</div>
								}
							}
							else
							{
								if (Model.Knowledge.Archived)
								{
									<div class="alert alert-danger d-flex align-items-center" role="alert">
										<svg class="bi flex-shrink-0" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill" /></svg>
										<div class="mx-2 fst-italic small">
											This experience has been archived and is not available for participation.
										</div>
									</div>
								}
								else if (Model.CanJoin)
								{
									<div class="alert alert-primary d-flex align-items-center" role="alert">
										<svg class="bi flex-shrink-0" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill" /></svg>
										<div class="mx-2 fst-italic small">
											This experience is available for you begin.
										</div>
									</div>
								}
							}
						</div>
					</div>
					
				</div>
				<div class="card-footer">
					@if (Model.Knowledge != null && Model.KnowledgeParticipation != null && Model.KnowledgeParticipation.Id > 0 && !Model.KnowledgeParticipation.IsComplete)
					{
						<button type="submit" class="btn btn-primary" value="Mark Complete" title="Click to mark the experience complete.">Mark Complete</button>
					}
					@if (Model.Knowledge != null && !Model.Knowledge.Archived && Model.KnowledgeParticipation == null && Model.CanJoin)
					{
						<button type="submit" asp-page-handler="join" asp-route-id="@Model.ID" class="btn btn-primary" value="Join" title="Click to join this experience.">Join</button>
					}
					@if (Model.KnowledgeParticipation != null && !Model.KnowledgeParticipation.IsComplete)
					{
						<button type="submit" asp-page-handler="leave" asp-route-id="@Model.ID" class="btn btn-danger" value="Leave" title="Click to leave this experience.">Leave</button>
					}
				</div>
			</div>
		</form>
	</div>
</div>
<div class="row my-3">
	<div class="col-6">
		<div class="card">
			<div class="card-header">
				Participation
			</div>
			<div class="card-body">
				<canvas id="skillParticipation" height="250"></canvas>
			</div>
		</div>
	</div>
	<div class="col-6">
		<div class="card">
			<div class="card-header">
				Average Time To Complete
			</div>
			<div class="card-body text-center">
				<div id="skillAvgCompletion" class="fs-1">?</div>
				<div class="text-muted">Rotations</div>
			</div>
		</div>
	</div>
</div>

<input type="hidden" id="knowledgeId" value="@Model.Knowledge?.Id" />
@section scripts {
	<script type="text/javascript" src="~/js/date.js"></script>
	<script type="text/javascript" src="~/lib/chartjs/Chart.js"></script>
	<script type="text/javascript" src="~/js/chartingDefaults.js" asp-append-version="true"></script>
	<script type="text/javascript" src="~/js/skills/dashboards.js" asp-append-version="true"></script>
	<script type="text/javascript" src="~/js/skills/details.js" asp-append-version="true"></script>
}