Holonet.Jedi.Academy.App/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Holonet.Jedi.Academy.App.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Holonet.Jedi.Academy.App/Pages/Home.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using Holonet.Jedi.Academy.Entities.Configuration;
using Holonet.Jedi.Academy.Entities.App;
using Microsoft.EntityFrameworkCore;
using Holonet.Jedi.Academy.Entities;

namespace Holonet.Jedi.Academy.App.Pages
{
    public class HomeModel : RazorPageDefaults
    {
        private IMemoryCache SiteCache;
        private readonly ILogger<HomeModel> _logger;
		private readonly Holonet.Jedi.Academy.BL.Data.AcademyContext _context;

		public IList<Quest> Quests { get; set; } = default!;

        public bool CompleteProfile { get; set; }

        public string ProfileIssuesJSON { get; set; } = string.Empty;

        public HomeModel(Holonet.Jedi.Academy.BL.Data.AcademyContext context, ILogger<HomeModel> logger, IOptions<SiteConfiguration> options, IHttpContextAccessor httpContextAccessor, IMemoryCache memoryCache) : base(options, httpContextAccessor)
        {
            _logger = logger;
            SiteCache = memoryCache;
            _context= context;
        }

        public async Task OnGetAsync()
        {
            IQueryable<Quest> questsIQ = from r in _context.Quests
                                         .Include(q => q.Rank)
                                         orderby r.Rank.RankLevel, r.Name
                                         select r;
            Quests = await questsIQ.Take(6).AsNoTracking().ToListAsync();
            UserAccount? currentUser = GetActiveUser();
            if (currentUser != null)
            {
                if (_context.UserProfiles.Any(x => x.UserId.Equals(currentUser.UserId)))
                {
                    UserProfile currentUserProfile = await _context.UserProfiles.Include(x=>x.Student).Where(x => x.UserId.Equals(currentUser.UserId)).FirstOrDefaultAsync();
                    if (currentUserProfile != null) 
                    { 
                        ProfileChecks(currentUserProfile); 
                    }
                }
            }

        }
        private void ProfileChecks(UserProfile profile)
        {
            if (profile != null)
            {
                List<string> issues = profile.GetProfileIssues();
                if (issues != null && issues.Count > 0)
                {
                    CompleteProfile = false;
                    var data = new { issues = issues };
                    ProfileIssuesJSON = Newtonsoft.Json.JsonConvert.SerializeObject(data);
                }
                else
                {
                    CompleteProfile = true;
                }
            }
            else
            {
                CompleteProfile = false;
                var data = new { issues = new List<string> { "A valid profile was not retrieved from the system." } };
                ProfileIssuesJSON = Newtonsoft.Json.JsonConvert.SerializeObject(data);
            }
        }
    }
}

Holonet.Jedi.Academy.App/Pages/Index.cshtml.cs
using Holonet.Jedi.Academy.BL.Session;
using Holonet.Jedi.Academy.Entities;
using Holonet.Jedi.Academy.Entities.Configuration;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace Holonet.Jedi.Academy.App.Pages
{
    public class IndexModel : RazorPageDefaults
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(IOptions<SiteConfiguration> options, IHttpContextAccessor httpContextAccessor, ILogger<IndexModel> logger): base(options, httpContextAccessor)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
			SessionHandler sessionHandler = new SessionHandler(CurrentHttpContext.HttpContext);
			UserSession? sessionObj = sessionHandler.GetSession();
			if (sessionObj != null && sessionObj.HasAcknowledgedConsent)
			{
				return RedirectToPage("./Home");
			}

			return Page();
		}
    }
}

Holonet.Jedi.Academy.App/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Holonet.Jedi.Academy.App.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Holonet.Jedi.Academy.App/Pages/Search.cshtml.cs
using Holonet.Jedi.Academy.BL.Search;
using Holonet.Jedi.Academy.BL.Session;
using Holonet.Jedi.Academy.Entities;
using Holonet.Jedi.Academy.Entities.App;
using Holonet.Jedi.Academy.Entities.Configuration;
using Holonet.Jedi.Academy.Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace Holonet.Jedi.Academy.App.Pages
{
    public class SearchModel : RazorPageDefaults
    {
        private readonly ILogger<SearchModel> _logger;
		private readonly Holonet.Jedi.Academy.BL.Data.AcademyContext _context;

		public SearchModel(Holonet.Jedi.Academy.BL.Data.AcademyContext context, IOptions<SiteConfiguration> options, IHttpContextAccessor httpContextAccessor, ILogger<SearchModel> logger): base(options, httpContextAccessor)
        {
            _logger = logger;
			_context = context;
		}

		public string NameSort { get; set; } = string.Empty;
		public string TypeSort { get; set; } = string.Empty;
		public string CurrentSort { get; set; } = string.Empty;
		public string SearchString { get; set; } = string.Empty;

		public PaginatedList<SearchResult> Results { get; set; } = default!;

		public async Task OnGetAsync(string search, string sortOrder, int? pageIndex)
		{
			if (String.IsNullOrEmpty(sortOrder))
				sortOrder = "Name";
			CurrentSort = sortOrder;
			SearchString = search;
			NameSort = sortOrder == "Name" ? "name_desc" : "Name";
			TypeSort = sortOrder == "Type" ? "type_desc" : "Type";
			SearchHandler searching = new SearchHandler(_context);
			IQueryable<SearchResult> resultsIQ = searching.ExecuteSearch(search);
			switch (sortOrder)
			{
				case "Name":
					resultsIQ = resultsIQ.OrderBy(s => s.Name);
					break;
				case "name_desc":
					resultsIQ = resultsIQ.OrderByDescending(s => s.Name);
					break;
				case "Type":
					resultsIQ = resultsIQ.OrderBy(s => s.Type);
					break;
				case "type_desc":
					resultsIQ = resultsIQ.OrderByDescending(s => s.Type);
					break;
				default:
					resultsIQ = resultsIQ.OrderBy(s => s.Name);
					break;
			}

			var pageSize = (Config.SiteSettings != null) ? Config.SiteSettings.PageSize : 10;
			Results = await PaginatedList<SearchResult>.CreateAsync(resultsIQ, pageIndex ?? 1, pageSize);
		}
	}
}

Holonet.Jedi.Academy.App/Pages/ThrowError.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Holonet.Jedi.Academy.App.Pages
{
    public class ThrowErrorModel : PageModel
    {
        public void OnGet()
        {
            throw new Exception("This is an exception that is thrown on purpose.", new Exception("This is the real reason why it was thrown..."));
        }
    }
}

Holonet.Jedi.Academy.App/Pages/UserProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Holonet.Jedi.Academy.BL.Data;
using Holonet.Jedi.Academy.Entities.App;
using Holonet.Jedi.Academy.Entities.Configuration;
using Microsoft.Extensions.Options;
using Holonet.Jedi.Academy.Entities;
using Holonet.Jedi.Academy.Entities.Models;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Holonet.Jedi.Academy.App.Pages
{
	public class UserProfileModel : RazorPageDefaults
	{
		private readonly Holonet.Jedi.Academy.BL.Data.AcademyContext _context;

		public UserProfileModel(Holonet.Jedi.Academy.BL.Data.AcademyContext context, IOptions<SiteConfiguration> options, IHttpContextAccessor httpContextAccessor) : base(options, httpContextAccessor)
		{
			_context = context;
		}

		[BindProperty]
		public UserProfileVM UserProfile { get; set; } = default!;

		public Student Student { get; set; } = default!;

		public List<QuestXP> PersonalQuests { get; set; } = default!;

		public List<KnowledgeXP> PersonalSkills { get; set; } = default!;

		public List<ForcePowerXP> ForcePowers { get; set; } = default!;

		public List<RewardPoint> RewardPoints { get; set; } = default!;

		public string RewardPointOutput
		{
			get
			{
				if(RewardPoints != null && RewardPoints.Count > 0)
				{
					if (RewardPoints.Count > 99)
						return "99+";
					else
						return RewardPoints.Count.ToString();
				}
				else
				{
					return "0";
				}
			}
		}

		public int StudentId { get; set; }

		[BindProperty]
		[Required]
		[Display(Name = "Skill Selection")]
		public int SelectedForcePowerId { get; set; }

		public string ButtonAction { get; set; } = string.Empty;

		public async Task<IActionResult> OnGetAsync()
		{
			UserAccount? currentUser = GetActiveUser();
			if (currentUser == null)
			{
				return NotFound();
			}
			UserProfile = new UserProfileVM();
			UserProfile userProfileDomain = new Entities.UserProfile();
			if (await UserProfileExists(currentUser.UserId))
			{
				userProfileDomain = await _context.UserProfiles
					.Include(x=>x.Student).ThenInclude(s=>s.Quests).ThenInclude(qxp=>qxp.Quest).ThenInclude(q=>q.Objectives).ThenInclude(qo=>qo.Objective).ThenInclude(o=>o.Destinations).ThenInclude(d=>d.Planet)
					.Include(x=>x.Student).ThenInclude(s=>s.Knowledge).ThenInclude(kxp=>kxp.Knowledge)
					.Include(x => x.Student).ThenInclude(s => s.ForcePowers).ThenInclude(fxp => fxp.ForcePower)
					.Include(x => x.Student).ThenInclude(s => s.Rank)
					.Where(x => x.UserId.Equals(currentUser.UserId)).FirstOrDefaultAsync();
				if (userProfileDomain != null)
				{
					UserProfile.Populate(userProfileDomain);
				}
				StudentId = userProfileDomain.StudentId;
				if(StudentId > 0)
				{
					Student = await _context.Students.FindAsync(StudentId);
				}
				else
				{
					Student = new Student() { Id = 0, Rank = await GetInitialRank() };
				}
				RewardPoints = await _context.RewardPoints.Where(x => x.StudentId.Equals(StudentId)).ToListAsync();				
				ButtonAction = "Update";
				List<int> excludeIds = userProfileDomain.Student.ForcePowers.Select(x=>x.ForcePowerId).ToList();
				ViewData["ForcePowers"] = new SelectList(await _context.ForcePowers
					.Include(fp=>fp.MinimumRank)
					.Where(x=> !x.Archived && !excludeIds.Contains(x.Id) && userProfileDomain.Student.Rank.RankLevel >= x.MinimumRank.RankLevel)
					.OrderBy(x => x.Name)
					.ToListAsync(), "Id", "Name");
			}
			else
			{
				StudentId = 0;
				Student = new Student() { Id=0, Rank = await GetInitialRank() };
				UserProfile.UserId = currentUser.UserId;
				UserProfile.FirstName = currentUser.FirstName;
				UserProfile.LastName = currentUser.LastName;
				ButtonAction = "Save";
				ViewData["ForcePowers"] = new SelectList(new List<ForcePower>(), "Id", "Name");
			}
			ViewData["Planets"] = new SelectList(await _context.Planets.Where(x=>!x.Archived).OrderBy(x => x.Name).ToListAsync(), "Id", "Name");
			ViewData["Species"] = new SelectList(await _context.AlienRaces.Where(x => !x.Archived).OrderBy(x => x.Name).ToListAsync(), "Id", "Name");
			PopulatePersonalProperties(userProfileDomain);
			return Page();
		}

		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see https://aka.ms/RazorPagesCRUD.
		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.GetFieldValidationState("UserProfile") != ModelValidationState.Valid)
			{
				return Page();
			}
			if (await UserProfileExists(UserProfile.Id))
			{
				var profileToUpdate = await _context.UserProfiles.FindAsync(UserProfile.Id);
				if (profileToUpdate == null)
				{
					return NotFound();
				}
				profileToUpdate.Student.PlanetId = UserProfile.PlanetId;
				profileToUpdate.Student.SpeciesId = UserProfile.SpeciesId;
				_context.Update(profileToUpdate);

				try
				{
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!await UserProfileExists(UserProfile.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
			}
			else
			{
				var emptyUserProfile = new UserProfile();
				emptyUserProfile.UserId = UserProfile.UserId;
				emptyUserProfile.Student = new Student();
				emptyUserProfile.Student.FirstName= UserProfile.FirstName;
				emptyUserProfile.Student.LastName= UserProfile.LastName;
				emptyUserProfile.Student.SpeciesId= UserProfile.SpeciesId;
				emptyUserProfile.Student.PlanetId = UserProfile.PlanetId;
				emptyUserProfile.Student.Experience = 0;
				emptyUserProfile.Student.InitiatedOn = DateTime.Now;
				emptyUserProfile.Student.Rank = await GetInitialRank();
				if (emptyUserProfile.Student.Rank != null)
				{
					emptyUserProfile.Student.RankId = emptyUserProfile.Student.Rank.Id;
				}
				
				_context.UserProfiles.Add(emptyUserProfile);
				await _context.SaveChangesAsync();
			}

			return RedirectToPage("UserProfile");
		}

		public async Task<IActionResult> OnPostNewSkillAsync(int studentId)
		{
			UserAccount? currentUser = GetActiveUser();
			if (currentUser == null)
			{
				return NotFound();
			}
			if (studentId > 0 && SelectedForcePowerId > 0)
			{
				var forcePower = await _context.ForcePowers.Include(fp => fp.MinimumRank).Where(x => !x.Archived && x.Id.Equals(SelectedForcePowerId)).FirstOrDefaultAsync();
				if (forcePower == null)
				{
					throw new Exception("The force power was invalid.");
				}
				var student = await _context.Students.Include(s => s.Rank).Where(x => x.Id.Equals(studentId)).FirstOrDefaultAsync();
				if (student == null)
				{
					throw new Exception("The student identifier was invalid.");
				}
				if (_context.ForcePowersLearned.Any(x=>x.ForcePowerId.Equals(SelectedForcePowerId) && x.StudentId.Equals(studentId)))
				{
					throw new Exception("The student has already obtained this force power.");
				}
				if (student.Rank != null && forcePower.MinimumRank != null && student.Rank.RankLevel < forcePower.MinimumRank.RankLevel)
				{
					throw new Exception("The student does not currently meet the minimum rank level for to learn this force power. Please try again later.");
				}
				var rewardPoint = await _context.RewardPoints.Where(x => x.StudentId.Equals(studentId)).FirstOrDefaultAsync();
				if (rewardPoint == null)
				{
					throw new Exception("The student does not currently possess any reward points. Please try again later.");
				}
				_context.RewardPoints.Remove(rewardPoint);
				_context.ForcePowersLearned.Add(new ForcePowerXP { ForcePowerId = SelectedForcePowerId, StudentId = studentId, GainedOn = DateTime.Now });
				await _context.SaveChangesAsync();
			}
			else
			{
				throw new Exception("The student or skill were invalid. Please try again.");
			}

			return RedirectToPage("UserProfile");
		}

		private async Task<bool> UserProfileExists(int id)
		{
			return await _context.UserProfiles.AnyAsync(e => e.Id == id);
		}

		private async Task<bool> UserProfileExists(string userId)
		{
			return await _context.UserProfiles.AnyAsync(e => e.UserId.Equals(userId));
		}

		private async Task<Rank> GetInitialRank()
		{
			Rank? initialRank = await _context.Ranks.OrderBy(x => x.RankLevel).FirstOrDefaultAsync();
			return (initialRank != null) ? initialRank : new Rank();
		}

		private void PopulatePersonalProperties(Entities.UserProfile userProfile)
		{
			PersonalQuests = userProfile.Student.Quests;
			PersonalSkills = userProfile.Student.Knowledge;
			ForcePowers = userProfile.Student.ForcePowers;
		}
	}
}

Holonet.Jedi.Academy.App/Pages/ThrowError.cshtml
@page
@model Holonet.Jedi.Academy.App.Pages.ThrowErrorModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Holonet.Jedi.Academy.App/Pages/UserProfile.cshtml
@page
@model Holonet.Jedi.Academy.App.Pages.UserProfileModel

@{
	ViewData["Title"] = "User Profile";
}
<div class="d-flex align-items-center justify-content-between">
	<h1>User Profile</h1>
	<div class="fs-1 ms-auto">
		@if (Model.RewardPoints != null && Model.RewardPoints.Count > 0)
		{
			<a id="newSkillSelector" href="javascript:void(0);" class="position-relative" title="Click to select a new skill!" data-bs-toggle="modal" data-bs-target="#skillSelectionModal">
				<i class="fas fa-star"></i>
				<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger fs-6">
					@Model.RewardPointOutput
					<span class="visually-hidden">reward points</span>
				</span>
			</a>
		}
		else
		{
			<a href="javascript:void(0);" class="disabled link-secondary" role="button" aria-disabled="true">
				<i class="fas fa-star"></i>
			</a>
		}
	</div>
</div>

<hr />
<div class="row">
	<div class="col-md-4">
		<form method="post">
			<div class="card">
				<div class="card-header">
					<h5>Personal Information</h5>
				</div>
				<div class="card-body">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<input type="hidden" asp-for="UserProfile.Id" />
					<input type="hidden" asp-for="UserProfile.UserId" />
					<div class="mb-3">
						<label asp-for="UserProfile.FirstName" class="control-label"></label>
						<input asp-for="UserProfile.FirstName" class="form-control" readonly />
						<span asp-validation-for="UserProfile.FirstName" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label asp-for="UserProfile.LastName" class="control-label"></label>
						<input asp-for="UserProfile.LastName" class="form-control" readonly />
						<span asp-validation-for="UserProfile.LastName" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label asp-for="UserProfile.SpeciesId" class="control-label"></label>
						<select asp-for="UserProfile.SpeciesId" class="form-select" asp-items="ViewBag.Species">
							<option value="">Select a species</option>
						</select>
						<span asp-validation-for="UserProfile.SpeciesId" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label asp-for="UserProfile.PlanetId" class="control-label"></label>
						<select asp-for="UserProfile.PlanetId" class="form-select" asp-items="ViewBag.Planets">
							<option value="">Select a planet</option>
						</select>
						<span asp-validation-for="UserProfile.PlanetId" class="text-danger"></span>
					</div>
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-primary">@Model.ButtonAction</button>
				</div>
			</div>
		</form>
		<h1><i class="far fa-star"></i></h1>
	</div>
	<div class="col-md-7 offset-md-1">
		<div class="card mb-2">
			<div class="card-header d-flex justify-content-between">
				<span class="fw-bold">
					Current Rank: <span class="badge bg-secondary">@Model.Student.Rank.Name</span>
				</span>
				<span class="fw-bold">Current Experience: <span class="badge bg-secondary">@Model.Student.Experience</span></span>
			</div>
			<div class="card-body d-flex justify-content-between align-items-center">
				<div class="text-center p-2">Minimum<br />@Model.Student.Rank.Minimum</div>
				<div class="p-2 flex-grow-1">
					<div class="progress">
						<div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: @Model.Student.RankProgress%" aria-valuenow="@Model.Student.RankProgress" aria-valuemin="0" aria-valuemax="100">
							@Model.Student.RankProgress%
						</div>
					</div>
				</div>
				<div class="text-center p-2">Maximum <br />@Model.Student.Rank.Maximum</div>
			</div>
		</div>
		
		<div class="card">
			<div class="card-header">
				<ul class="nav nav-tabs card-header-tabs" id="profileTabs" role="tablist">
					<li class="nav-item" role="presentation">
						<button class="nav-link active" id="quests-tab" data-bs-toggle="tab" data-bs-target="#quests" type="button" role="tab" aria-controls="quests" aria-selected="true">Quests</button>
					</li>
					<li class="nav-item" role="presentation">
						<button class="nav-link" id="skills-tab" data-bs-toggle="tab" data-bs-target="#skills" type="button" role="tab" aria-controls="skills" aria-selected="false">Experience (Skills)</button>
					</li>
					<li class="nav-item" role="presentation">
						<button class="nav-link" id="powers-tab" data-bs-toggle="tab" data-bs-target="#powers" type="button" role="tab" aria-controls="powers" aria-selected="false">Force Powers</button>
					</li>
				</ul>
			</div>
			<div class="card-body">
				<div class="tab-content" id="profileTabsContent">
					<div class="tab-pane fade show active" id="quests" role="tabpanel" aria-labelledby="quests-tab">
						<div class="list-group">
							@foreach (var item in Model.PersonalQuests)
							{
								<a href="/Quests/Details?id=@item.Quest.Id" class="list-group-item list-group-item-action" aria-current="true">
									<div class="d-flex w-100 justify-content-between">
										<div><h5 class="mb-1">@item.Quest.Name</h5></div>
										<div>
											@if (item.IsComplete)
											{
												<span class="badge rounded-pill bg-success">@item.Status</span>
											}
											else
											{
												<span class="badge rounded-pill bg-warning text-dark">@item.Status</span>
											}
										</div>
									</div>
									<p class="mb-1">@item.Quest.ShortDescription</p>
									@foreach (var dest in item.Quest.DestinationPlanets())
									{
										<span class="badge bg-secondary">@Html.Raw(dest.Name)</span>
									}

								</a>
							}
						</div>
					</div>
					<div class="tab-pane fade" id="skills" role="tabpanel" aria-labelledby="skills-tab">
						<div class="list-group">
							@foreach (var item in Model.PersonalSkills)
							{
								<a href="/Experience/Details?id=@item.Knowledge.Id" class="list-group-item list-group-item-action" aria-current="true">
									<div class="d-flex w-100 justify-content-between">
										<h5 class="mb-1">@item.Knowledge.Name</h5>
										<small>@item.Status</small>
									</div>
									<p class="mb-1">@item.Knowledge.Description</p>
								</a>
							}
						</div>
					</div>
					<div class="tab-pane fade" id="powers" role="tabpanel" aria-labelledby="powers-tab">
						<div class="list-group">
							@foreach (var item in Model.ForcePowers)
							{
								<a href="/References/ForcePowers/Details?id=@item.ForcePower.Id" class="list-group-item list-group-item-action" aria-current="true">
									<div class="d-flex align-items-center justify-content-between">
										<h5 class="mb-1">@item.ForcePower.Name</h5>
										<div class="ms-auto">Gained On: <span class="badge bg-secondary">@Html.DisplayFor(modelItem=>item.GainedOn)</span></div>
									</div>
									<div class="text-muted">@item.ForcePower.Description</div>
								</a>
							}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="skillSelectionModal" tabindex="-1" aria-labelledby="skillSelectionModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form method="post" asp-page-handler="newskill" asp-route-studentId="@Model.StudentId">
				<div class="modal-header">
					<h5 class="modal-title" id="skillSelectionModalLabel">New Skill Selection</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<div class="mb-3">
						<label asp-for="SelectedForcePowerId" class="control-label"></label>
						<select asp-for="SelectedForcePowerId" class="form-select" asp-items="ViewBag.ForcePowers">
							<option value="">Select a power to learn</option>
						</select>
						<span asp-validation-for="SelectedForcePowerId" class="text-danger"></span>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Select</button>
				</div>
			</form>
		</div>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	<script type="text/javascript" src="~/js/UserProfile.js" asp-append-version="true"></script>
}